name: terraform-fmt

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
        with:
          terraform_version: 1.2.8
          terraform_wrapper: false
      - name: Check tf files
        run: |
          make fmt
